kind: PersistentVolume
apiVersion: v1
metadata:
  name: manually-created-vol1
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: "vol-039a96b2911716438"
    fsType: ext4
