apiVersion: v1
kind: PersistentVolume
metadata:
  name: aws-pv-01
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    fsType: ext4
    volumeID: vol-073753dfca7a2e970
