apiVersion: v1
kind: Service
metadata:
  name: activemq
  labels:
    app: activemq
spec:
  ports:
    - port: 8161
  selector:
    app: activemq
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: amq-claim
  labels:
    app: activemq
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: activemq
  labels:
    app: activemq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: activemq
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: activemq
        tier: frontend
    spec:
      containers:
      - image: activemq:1.0
        name: activemq
        #resources:
        #  requests:
        #    memory: "1Gi"
        #    cpu: "0.5"
        ports:
        - containerPort: 8161
          name: activemq
        volumeMounts:
        - name: activemq-persistent-storage
          mountPath: /opt/activemq
      volumes:
      - name: activemq-persistent-storage
        persistentVolumeClaim:
          claimName: amq-claim

