apiVersion: apps/v1
kind: Deployment
metadata:
  name: activemq-deployment-local
  labels:
    app: activemq
spec:
  replicas: 2
  selector:
    matchLabels:
      app: activemq
  template:
    metadata:
      labels:
        app: activemq
    spec:
      containers:
      - name: activemq
        image: activemq:1.0
        ports:
        - containerPort: 8161
        volumeMounts:
        - name: activemq-data-local
          mountPath: /opt/apache-activemq-5.15.6/data
          readOnly: false
      volumes:
      - name: activemq-data-local
        persistentVolumeClaim:
          claimName: amq-pv-claim-local
      - name: config-vol
        configMap:
          name: amq-config-map 
---
apiVersion: v1
kind: Service
metadata:
  name: my-service-local
spec:
  selector:
    app: activemq
  ports:
  - port: 8161
    targetPort: 8161
  type: NodePort
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: amq-pv-claim-local
spec:
  # If this is manual, it expects us to create the PV first
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: amq-pv-claim-local
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp
