# Status:
# This description file will create a single pod which can be accessed from
# each nodes ip address at the port exposed by the NodePort service
#
# Only the Persistent volume claim needs to be specified.  A PV is automatically
# created in aws
#
# Limitation:  Only one pod can be launched. If replicas number is increased
# one pod is running while the other is waiting. 
#
# No need to worry about the config map listed.  no config map exists and this works
#


apiVersion: apps/v1
kind: Deployment
metadata:
  name: activemq-deployment
  labels:
    app: activemq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: activemq
  template:
    metadata:
      labels:
        app: activemq
    spec:
      securityContext:
        fsGroup: 2000
      containers:
      - name: activemq
        image: activemq:1.0
        ports:
        - containerPort: 8161
        volumeMounts:
        - name: activemq-data
          mountPath: /opt/apache-activemq-5.15.6/data
          readOnly: false
      volumes:
      - name: activemq-data
        persistentVolumeClaim:
          claimName: amq-pv-claim
#      - name: config-vol
#        configMap:
#          name: amq-config-map
---
apiVersion: v1
kind: Service
metadata:
  name: amq-nodeport-service
spec:
  selector:
    app: activemq
  ports:
  - port: 8161
    targetPort: 8161
  type: NodePort
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: amq-pv-claim
spec:
  #storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
#---
#kind: PersistentVolume
#apiVersion: v1
#metadata:
#  name: amq-pv-claim
#  labels:
#    type: local
#spec:
#  storageClassName: manual
#  capacity:
#    storage: 3Gi
#  accessModes:
#    - ReadWriteOnce
#  hostPath:
#    path: /tmp
